// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5RM5BkW-nO0KecWW4KYBbBYvPvwEBQU',
    appId: '1:247965598091:web:a97a378ede8c008eaf6f8e',
    messagingSenderId: '247965598091',
    projectId: 'spendtax-9f171',
    authDomain: 'spendtax-9f171.firebaseapp.com',
    databaseURL: 'https://spendtax-9f171.firebaseio.com',
    storageBucket: 'spendtax-9f171.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWJRkvpveOrIk_8mKTN3qcGWD031ouZs',
    appId: '1:247965598091:android:d70aa0dea751f39baf6f8e',
    messagingSenderId: '247965598091',
    projectId: 'spendtax-9f171',
    databaseURL: 'https://spendtax-9f171.firebaseio.com',
    storageBucket: 'spendtax-9f171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPcZvTxI-vixAw_mmKh_7TP3EiKikHdoU',
    appId: '1:247965598091:ios:784ed182323ceb33af6f8e',
    messagingSenderId: '247965598091',
    projectId: 'spendtax-9f171',
    databaseURL: 'https://spendtax-9f171.firebaseio.com',
    storageBucket: 'spendtax-9f171.appspot.com',
    androidClientId: '247965598091-0o04tgfpn4fcbpru035knj55hqba6s35.apps.googleusercontent.com',
    iosClientId: '247965598091-3c0poofn79ihemr0825ce6v6ekf39ogj.apps.googleusercontent.com',
    iosBundleId: 'com.example.piggy',
  );
}
